### ISSUE TITLE
Problem with plotting

### ISSUE THREAD

**Issue by brasmus** [metno/esd#120]
Recent changes in plot/map has introduced a new bug:
 
```r2
sa24 <- retrieve('~/Downloads/sa24daily1940-2012.nc',param='precip',
                  lon=c(-50,-32),lat=c(-20,0))
X <- annual(sa24,FUN='sum')
nino3.4 <- NINO3.4()
y <- annual(nino3.4,FUN='max')
eof <- EOF(X)
 z <- DS(y,eof)
plot(z)
###Error in attr(x, "pattern")[, , pattern] : incorrect number of dimensions
```

**Comment by kajsamp** [comment]
The downscaled results in z are for some reason assigned the class eof and field. Is this intentional? It doesn't seem right because when you then plot you will use plot.ds.eof which doesn't work as z doesn't have the right attributes to be plotted as an eof. If you remove eof and field from the class(z) it plots just fine.

**Comment by abdelkaderm** [comment]
I think the bug comes from 'eof' class that is assigned to 'z'. Will try to fix it and let you know

**Comment by abdelkaderm** [comment]
Also, I think that having both type of class `eof` and `field` is sometimes confusing !

**Comment by abdelkaderm** [comment]
Hi there, 

I have removed `eof`class attribution from the returned `DS` object. It seems to work but I do not know how this will affect the other functionalities.

Bests,
