### ISSUE TITLE
error in retrieve.ncdf4

### ISSUE THREAD

**Issue by anitavd** [metno/esd#150]
I try this command:
retrieve.ncdf4("/vol/klimadata/work/rasmusb/data/ERA40/ERA40_t2m_mon.nc",  lon = c(4, 34), lat = c(54, 84))

and get the following error:
promise already under evaluation: recursive default argument reference or earlier problems?

it seems to be related to lon and lat

**Comment by abdelkaderm** [comment]
Hi there, 

I tried the following and did not get any error !
```r
 t2m.era40 <- retrieve.ncdf4("/vol/klimadata/work/rasmusb/data/ERA40/ERA40_t2m_mon.nc", lon = c(4, 34), lat = c(54, 84),path='') 
map(yy,colbar=list(col=colscal(n=20)))
```
The result is at  
[t2m.era40.pdf](https://github.com/metno/esd/files/97439/t2m.era40.pdf)

**Comment by anitavd** [comment]
Thanks. The path=' ' fixed it. But that's not very intuitive :) Maybe write something about it in the help?

**Comment by abdelkaderm** [comment]
Hi there, sorry for the late reply on this comment. Yes, you are defintely correct, setting the `path` to `path=''` is not intuitive. I would personally use the default retrieve function rather than `retrieve.ncdf4`. The former deals with paths and filename and type more efficiently. Also, you can specify which Netcdf library to use by setting the argument `type` to `type='ncdf4'`. Something like the following
```r
t2m.era40 <- retrieve("/vol/klimadata/work/rasmusb/data/ERA40/ERA40_t2m_mon.nc", lon = c(4, 34), lat = c(54, 84),type='ncdf4') 
```

**Comment by abdelkaderm** [comment]
Hi,
I fixed the bug in `retrieve.ncdf4`, now both ways of retrieving the data should work :+1: 
Mvh
