### ISSUE TITLE
Problems reading station data

### ISSUE THREAD

**Issue by brasmus** [metno/esd#192]
Errors/warnings with following: 

```r2
ss <- select.station(src=c('ghcnd','ecad'),lat=c(30,70),nmin=65)
  ss$start <- as.numeric(ss$start)
  ss$end <- as.numeric(ss$end)
  keep <- (ss$end >= 2010)
  ss <- ss[keep,]
  t2m <- station(ss)
```

e.g. `"Warning : No values found in the time series -> This station will be ignored"
[1] "994 TMAX 11077 SASSEUVA SPAIN ECAD"`

With `ss <- select.station(src='ghcnd',lat=c(30,70),nmin=65)` the call gets data from the GHCN, there is a bug in the use of `c()` and in reading mean temperature from ECAD, which are stored in `tg`.

**Comment by brasmus** [comment]
It works for `TMIN`but not for `TMAX`. 

I have made a crude 'bug-rectification' (unsatisfactory 'dirty' fix) to bypass this bug:

`if (toupper(param[i])=='TMAX') param[] <- 'tx' #REB 2016-07-26: dirty bug-rectification`

**Comment by abdelkaderm** [comment]
Hi Rasmus,

I did not get what was the error, it works fine for me. The reason for getting warnings is that sometime the meta data exist but the station contains no data to be retrieved. Thus, the function will return a warning and skip that station from the outcome. Yo may also need to specify the parameter and the data source, otherwise, the function will retrieve by default all parameters from all available sources e.g.
```r
apply(as.matrix(levels(factor(ss$element))),1,ele2param)
```
The ele2param function converts between element identifier and esd parameter.

Bests,

**Comment by kajsamp** [comment]
I had a different problem with `station`. The folder data.ECAD was not created before downloading data into that path which caused problems with `download.file`. Added a line to fix this.
