### ISSUE TITLE
problem installing ESD package

### ISSUE THREAD

**Issue by Ahmadffrahmand** [metno/esd#254]
Respected Sir,
i have a problem installing Esd even i installed ncdf4 and zoo pacakge as well. could you please see the errors i got below.

byte-compile and prepare package for lazy loading
Error: (converted from warning) package 'zoo' was built under R version 3.6.3
Execution halted
ERROR: lazy loading failed for package 'esd'
* removing 'C:/Users/Ahmad/Documents/R/win-library/3.6/esd'
Error: Failed to install 'esd' from GitHub:
  (converted from warning) installation of package ‘C:/Users/Ahmad/AppData/Local/Temp/RtmpSo3k0k/file1e5c15894922/esd_1.9.46.tar.gz’ had non-zero exit status

**Comment by brasmus** [comment]
The problem seems to be that you have an ld version of R and that package 'zoo' was built under R version 3.6.3. If you type `sessionInfo()`you will find out which version you are using. It may be an idea to install the latest version of **R** from [](https://cran.r-project.org). Perhaps also install the latest version of R-studio.

**Comment by brasmus** [comment]
Try to install esd from compiled packages available from https://drive.google.com/drive/folders/1mUkpH50DFISWzL71I4eXO17eQ7_Vi2wu
