### ISSUE TITLE
Problem in "combine" function in esd

### ISSUE THREAD

**Issue by javakh** [metno/esd#45]
There is something wrong in combine function given in esd. For example,

I'm taking to data sets t2m.NCEP and t2m.NorESM.M in the period 1948 to 2012.
latitude(30,70),longitude(-40,40).
so the dimensions of  t2m.NCEP and t2m.NorESM.M are( 780 x 561) and( 780 x 512) respectively.
Now I'm combining two two fields using "combine" function. It is expected the dimension of combined field should be (780 x (561+512)) i.e. (780 x 1073).
(Ref:statistic_method_for_signal_detection,Silvia .A.Venegas,page-47) 
But we are getting in esd that dimension of combined field is (780 x 561) which is nothing but dimension of  t2m.NCEP and this is not expected.

So, please help me to fix the problem

**Comment by abdelkaderm** [comment]
Hi ! 

There is nothing wrong in combine function for fields. it says in the documentation that
> For fields, ‘combine.field’ is used to append different data sets,  e.g. for the purpose of computing common EOFs (see ‘EOF’ or for mixing fields (coupled EOFs).

Basically, in your case you would like to combine NCEP with NorESM 2m-temperatures. Let's NCEP be field 1 (f1) and NorESM be field 2 (f2). 
```r
t2m.NCEP <- t2m.NCEP(lon=c(-40,40),lat=c(30,70))
t2m.NORE <- t2m.NorESM.M(lon=c(-40,40),lat=c(30,70))
f1 <- subset(t2m.NCEP,it=c(1948,2012))
f2 <- subset(t2m.NORE,it=c(1948,2012))
comb <- combine(f1,f2) 
```
When you use `combine(f1,f2)`  the function `combine` will only append the two fields' information for further processing and the corresponding original formats are kept. The function will return (f1) with additional attributes : 'appendix.1' which corresponds to (f2) and n.apps which corresponds to the number of extra field (n.apps = 1, in this case)

```r
# To display the attribute names for f1, type
names(attributes(f1))
 ```
> 
[1] "dim"        "index"      "class"      "variable"   "longname"  
[6] "unit"       "source"     "longitude"  "latitude"   "greenwich" 
[11] "calendar"   "type"       "aspect"     "reference"  "history"   
[16] "dimensions"

```r
# To display the attribute names for the comb*ined field, type
names(attributes(comb))
 ```
> 
[1] "dim"        "index"      "class"      "variable"   "longname"  
[6] "unit"       "source"     "longitude"  "latitude"   "greenwich" 
[11] "calendar"   "type"       "aspect"     "reference"  "history"   
[16] "dimensions" "appendix.1" "n.apps" 

The real combination of the two fields is done within the `EOF()` functions. For common EOF (e.g. similar to :statistic_method_for_signal_detection,Silvia .A.Venegas,page-47) , the combination is done when the `EOF(comb)` is called i.e. the real combination of the two field to get one matrix with dimension (e.g. 780 x 1073 in your case). Even so, the two fields will be returned separately from the EOF. The extra field information (f2, in this case) will be stored in 'appendix.1'

```r
eof <- EOF(comb)
plot(eof)
```

Hope this is clear !

**Comment by javakh** [comment]
Thank you very much for your elaborate reply. I understand that real
combination can  be done after EOF(comb). But one thing is still not clear
to me.If we make data frame of the object "comb" (as.data.frame(comb)) we
are getting a matrix of similar dimension of f1. Now what is this  newly
formed matrix???
And also if we combine (f2,f1) instead of combine(f1,f2) we are getting
different results.What is the reason behind this??

**Comment by abdelkaderm** [comment]
The real combination is done by `EOF()` but you don't see it. If you com*ine(f2,f1), you will get the same object f2 as output with f1 as an extra field. 

If you apply, as.data.frame on `comb` object, you will get the matrix or values from the first argument in `comb()` call converted to a data frame. For instance, as.data.frame(comb(f1,f2)) will only return f1 core data and as.data.frame(comb(f2,f1)) will only return f2 core data as data. Each data in the data frame will correspond to the lon x lat grid values for a specific date 1, 2, ...
The meaning of 'combine' in esd is different to the columns or rows combination as it only appends the data (or mix the data) so that it is well digested in the 'esd' later on and only used for further processing as the real combination is done later on. 
But if you would like to combine columns or rows, you may use `cbind()` or `rbind()` functions applied to a field object but these are not finished yet, as the combination does not include yet the attributes.  

```r
comb <- cbind(f1,f2)
```
> [1] "unfinished - need to combine the attributes from all inputs"

and the dimension of comb2 will be then, 
```r
dim(comb) 
``` 
> [1]  780 1073

**Comment by javakh** [comment]
Thanks again. I have understood your point.
Now if we use combine(f2,f1) for  downscaling (using DS function following
EOF(comb)) we get different downscaling results from that of combine(f1,f2)

now if f1 is reanalysis and f2 is gcm,then we are getting downscaling
results highly correlated with observation after combine (f1,f2) but
getting low correlated results if we use combine(f2,f1).Why this is
happening???? and what should we use combine(f1,f2) or combine(f2,f1) for
downscaling?????

**Comment by abdelkaderm** [comment]
Yes, definitely, 
1. as the first argument will be considered as observations or pseudo-observations and is used for calibration purposes. 
2. if f1 is reanalysis and f2 is gcm, f1 should be at first position as mentioned in point 1 because it is used to calibrate the DS model. To clarify, one could do the downscaling based on reanalysis only, in this case you can refer to Example 1 in the wiki pages, section "Downscaling" [](https://github.com/metno/esd/wiki/4.-Downscaling-%28in-progress%29). If you use combine, this means that the method used for downscaling is based on common EOF (between reanalysis and gcm)
3. When you use comb(f2,f1), the calibration is based on gcm results and we are in the gcm world, which has it's own climatology and do not correspond to reality if the forcing is not driven by reanalysis datasets.

**Comment by javakh** [comment]
Thanks a lot. It's quite clear now. :-)
